import {
	AtIcon,
	CirclePasswordIcon,
	EyeOff,
	FingerprintPatternIcon,
	Mail01Icon,
	ViewIcon,
	EyeOffIcon,
	SidebarRightIcon,
	GraduationCapIcon,
	Settings03Icon,
	Home03Icon,
	Quiz04Icon,
	File02Icon,
	BubbleChatQuestionIcon,
	Profile02Icon,
	UsersRoundIcon,
	UserCircleIcon,
	GridViewIcon,
	Search01Icon,
	TimeQuarter02Icon,
	CheckIcon,
	Pen01Icon,
	Rocket01Icon,
	LoginMethodIcon,
	TeacherIcon,
	AiScanIcon,
	DashboardSquare02Icon,
	Shield01Icon,
	ComputerPhoneSyncIcon,
	BubblesIcon,
	CheckmarkCircle02Icon,
	DatabaseIcon,
	ServerIcon,
	AlignSelectionIcon,
	Github01Icon,
  Linkedin01Icon,
  NewTwitterIcon,        // أو TwitterIcon
  InstagramIcon,
  YoutubeIcon,
  TelegramIcon,
  WhatsappIcon,
  DiscordIcon,
  Facebook01Icon,
  TiktokIcon,
  Location01Icon,
  ArrowLeft01Icon,
	AlertCircleIcon
} from '@hugeicons/core-free-icons';

export const icons = {
	loginFinger: FingerprintPatternIcon,
	At: AtIcon,
	mail: Mail01Icon,
	password: CirclePasswordIcon,
	eyeOn: ViewIcon,
	eyeOff: EyeOffIcon,
	grade: GraduationCapIcon,
	side: SidebarRightIcon,
	home: Home03Icon,
	question: BubbleChatQuestionIcon,
	exam: File02Icon,
	result: Quiz04Icon,
	users: UsersRoundIcon,
	settings: Settings03Icon,
	user: UserCircleIcon,
	profile: Profile02Icon,
	contact: GridViewIcon,
	search: Search01Icon,
	time: TimeQuarter02Icon,
	check: CheckIcon,
	circleCheck: CheckmarkCircle02Icon,
	pen: Pen01Icon,
	ai: AiScanIcon,
	rocket: Rocket01Icon,
	login: LoginMethodIcon,
	teacher: TeacherIcon,
	dashboard: DashboardSquare02Icon,
	shield: Shield01Icon,
	responsev: ComputerPhoneSyncIcon,
	bubbles: BubblesIcon,
	database: DatabaseIcon,
	server: ServerIcon,
	frame: AlignSelectionIcon,
	github: Github01Icon,
  linkedin: Linkedin01Icon,
  twitter: NewTwitterIcon,
  instagram: InstagramIcon,
  youtube: YoutubeIcon,
  telegram: TelegramIcon,
  whatsapp: WhatsappIcon,
  discord: DiscordIcon,
  facebook: Facebook01Icon,
  tiktok: TiktokIcon,
  location: Location01Icon,
  arrowLeft: ArrowLeft01Icon,
	notFound: AlertCircleIcon
};
